set_property PACKAGE_PIN R14 [get_ports {occupancy[0]}]
set_property PACKAGE_PIN P14 [get_ports {occupancy[1]}]
set_property PACKAGE_PIN N16 [get_ports {occupancy[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {occupancy[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {occupancy[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {occupancy[0]}]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN G17 [get_ports empty_alarm]
set_property PACKAGE_PIN M15 [get_ports max_limit]
set_property PACKAGE_PIN M20 [get_ports rst_n]
set_property PACKAGE_PIN Y18 [get_ports sensor_a]
set_property PACKAGE_PIN Y19 [get_ports sensor_b]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports empty_alarm]
set_property IOSTANDARD LVCMOS33 [get_ports max_limit]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sensor_a]
set_property IOSTANDARD LVCMOS33 [get_ports sensor_b]


